/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.InboundConfig;
import org.openapitools.client.model.InboundConfigsIdPutRequest;
import org.openapitools.client.model.InboundConfigsPostRequest;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InboundApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public InboundApi() {
        this(Configuration.getDefaultApiClient());
    }

    public InboundApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for inboundConfigsGet
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of inbound configs </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inboundConfigsGetCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/inbound/configs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call inboundConfigsGetValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return inboundConfigsGetCall(_callback);

    }

    /**
     * List inbound webhook configs
     * Returns all inbound webhook configurations for the authenticated user
     * @return List&lt;InboundConfig&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of inbound configs </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public List<InboundConfig> inboundConfigsGet() throws ApiException {
        ApiResponse<List<InboundConfig>> localVarResp = inboundConfigsGetWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * List inbound webhook configs
     * Returns all inbound webhook configurations for the authenticated user
     * @return ApiResponse&lt;List&lt;InboundConfig&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of inbound configs </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<InboundConfig>> inboundConfigsGetWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = inboundConfigsGetValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<InboundConfig>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List inbound webhook configs (asynchronously)
     * Returns all inbound webhook configurations for the authenticated user
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of inbound configs </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inboundConfigsGetAsync(final ApiCallback<List<InboundConfig>> _callback) throws ApiException {

        okhttp3.Call localVarCall = inboundConfigsGetValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<InboundConfig>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for inboundConfigsIdDelete
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Config deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inboundConfigsIdDeleteCall(@javax.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/inbound/configs/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call inboundConfigsIdDeleteValidateBeforeCall(@javax.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling inboundConfigsIdDelete(Async)");
        }

        return inboundConfigsIdDeleteCall(id, _callback);

    }

    /**
     * Delete inbound config
     * 
     * @param id  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Config deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public void inboundConfigsIdDelete(@javax.annotation.Nonnull UUID id) throws ApiException {
        inboundConfigsIdDeleteWithHttpInfo(id);
    }

    /**
     * Delete inbound config
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Config deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> inboundConfigsIdDeleteWithHttpInfo(@javax.annotation.Nonnull UUID id) throws ApiException {
        okhttp3.Call localVarCall = inboundConfigsIdDeleteValidateBeforeCall(id, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete inbound config (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Config deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inboundConfigsIdDeleteAsync(@javax.annotation.Nonnull UUID id, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = inboundConfigsIdDeleteValidateBeforeCall(id, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for inboundConfigsIdPut
     * @param id  (required)
     * @param inboundConfigsIdPutRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Config updated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inboundConfigsIdPutCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable InboundConfigsIdPutRequest inboundConfigsIdPutRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = inboundConfigsIdPutRequest;

        // create path and map variables
        String localVarPath = "/inbound/configs/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call inboundConfigsIdPutValidateBeforeCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable InboundConfigsIdPutRequest inboundConfigsIdPutRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling inboundConfigsIdPut(Async)");
        }

        return inboundConfigsIdPutCall(id, inboundConfigsIdPutRequest, _callback);

    }

    /**
     * Update inbound config
     * 
     * @param id  (required)
     * @param inboundConfigsIdPutRequest  (optional)
     * @return InboundConfig
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Config updated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public InboundConfig inboundConfigsIdPut(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable InboundConfigsIdPutRequest inboundConfigsIdPutRequest) throws ApiException {
        ApiResponse<InboundConfig> localVarResp = inboundConfigsIdPutWithHttpInfo(id, inboundConfigsIdPutRequest);
        return localVarResp.getData();
    }

    /**
     * Update inbound config
     * 
     * @param id  (required)
     * @param inboundConfigsIdPutRequest  (optional)
     * @return ApiResponse&lt;InboundConfig&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Config updated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InboundConfig> inboundConfigsIdPutWithHttpInfo(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable InboundConfigsIdPutRequest inboundConfigsIdPutRequest) throws ApiException {
        okhttp3.Call localVarCall = inboundConfigsIdPutValidateBeforeCall(id, inboundConfigsIdPutRequest, null);
        Type localVarReturnType = new TypeToken<InboundConfig>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update inbound config (asynchronously)
     * 
     * @param id  (required)
     * @param inboundConfigsIdPutRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Config updated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inboundConfigsIdPutAsync(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable InboundConfigsIdPutRequest inboundConfigsIdPutRequest, final ApiCallback<InboundConfig> _callback) throws ApiException {

        okhttp3.Call localVarCall = inboundConfigsIdPutValidateBeforeCall(id, inboundConfigsIdPutRequest, _callback);
        Type localVarReturnType = new TypeToken<InboundConfig>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for inboundConfigsPost
     * @param inboundConfigsPostRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Config created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inboundConfigsPostCall(@javax.annotation.Nonnull InboundConfigsPostRequest inboundConfigsPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = inboundConfigsPostRequest;

        // create path and map variables
        String localVarPath = "/inbound/configs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call inboundConfigsPostValidateBeforeCall(@javax.annotation.Nonnull InboundConfigsPostRequest inboundConfigsPostRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'inboundConfigsPostRequest' is set
        if (inboundConfigsPostRequest == null) {
            throw new ApiException("Missing the required parameter 'inboundConfigsPostRequest' when calling inboundConfigsPost(Async)");
        }

        return inboundConfigsPostCall(inboundConfigsPostRequest, _callback);

    }

    /**
     * Create inbound webhook config
     * 
     * @param inboundConfigsPostRequest  (required)
     * @return InboundConfig
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Config created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public InboundConfig inboundConfigsPost(@javax.annotation.Nonnull InboundConfigsPostRequest inboundConfigsPostRequest) throws ApiException {
        ApiResponse<InboundConfig> localVarResp = inboundConfigsPostWithHttpInfo(inboundConfigsPostRequest);
        return localVarResp.getData();
    }

    /**
     * Create inbound webhook config
     * 
     * @param inboundConfigsPostRequest  (required)
     * @return ApiResponse&lt;InboundConfig&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Config created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InboundConfig> inboundConfigsPostWithHttpInfo(@javax.annotation.Nonnull InboundConfigsPostRequest inboundConfigsPostRequest) throws ApiException {
        okhttp3.Call localVarCall = inboundConfigsPostValidateBeforeCall(inboundConfigsPostRequest, null);
        Type localVarReturnType = new TypeToken<InboundConfig>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create inbound webhook config (asynchronously)
     * 
     * @param inboundConfigsPostRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Config created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inboundConfigsPostAsync(@javax.annotation.Nonnull InboundConfigsPostRequest inboundConfigsPostRequest, final ApiCallback<InboundConfig> _callback) throws ApiException {

        okhttp3.Call localVarCall = inboundConfigsPostValidateBeforeCall(inboundConfigsPostRequest, _callback);
        Type localVarReturnType = new TypeToken<InboundConfig>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for inboundProviderEndpointIdPost
     * @param provider  (required)
     * @param endpointId  (required)
     * @param body  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook accepted </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inboundProviderEndpointIdPostCall(@javax.annotation.Nonnull String provider, @javax.annotation.Nonnull UUID endpointId, @javax.annotation.Nonnull Object body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/inbound/{provider}/{endpoint_id}"
            .replace("{" + "provider" + "}", localVarApiClient.escapeString(provider.toString()))
            .replace("{" + "endpoint_id" + "}", localVarApiClient.escapeString(endpointId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call inboundProviderEndpointIdPostValidateBeforeCall(@javax.annotation.Nonnull String provider, @javax.annotation.Nonnull UUID endpointId, @javax.annotation.Nonnull Object body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'provider' is set
        if (provider == null) {
            throw new ApiException("Missing the required parameter 'provider' when calling inboundProviderEndpointIdPost(Async)");
        }

        // verify the required parameter 'endpointId' is set
        if (endpointId == null) {
            throw new ApiException("Missing the required parameter 'endpointId' when calling inboundProviderEndpointIdPost(Async)");
        }

        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling inboundProviderEndpointIdPost(Async)");
        }

        return inboundProviderEndpointIdPostCall(provider, endpointId, body, _callback);

    }

    /**
     * Receive inbound webhook for a specific endpoint
     * 
     * @param provider  (required)
     * @param endpointId  (required)
     * @param body  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook accepted </td><td>  -  </td></tr>
     </table>
     */
    public void inboundProviderEndpointIdPost(@javax.annotation.Nonnull String provider, @javax.annotation.Nonnull UUID endpointId, @javax.annotation.Nonnull Object body) throws ApiException {
        inboundProviderEndpointIdPostWithHttpInfo(provider, endpointId, body);
    }

    /**
     * Receive inbound webhook for a specific endpoint
     * 
     * @param provider  (required)
     * @param endpointId  (required)
     * @param body  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook accepted </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> inboundProviderEndpointIdPostWithHttpInfo(@javax.annotation.Nonnull String provider, @javax.annotation.Nonnull UUID endpointId, @javax.annotation.Nonnull Object body) throws ApiException {
        okhttp3.Call localVarCall = inboundProviderEndpointIdPostValidateBeforeCall(provider, endpointId, body, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Receive inbound webhook for a specific endpoint (asynchronously)
     * 
     * @param provider  (required)
     * @param endpointId  (required)
     * @param body  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook accepted </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inboundProviderEndpointIdPostAsync(@javax.annotation.Nonnull String provider, @javax.annotation.Nonnull UUID endpointId, @javax.annotation.Nonnull Object body, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = inboundProviderEndpointIdPostValidateBeforeCall(provider, endpointId, body, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for inboundProviderPost
     * @param provider  (required)
     * @param body  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid payload </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inboundProviderPostCall(@javax.annotation.Nonnull String provider, @javax.annotation.Nonnull Object body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/inbound/{provider}"
            .replace("{" + "provider" + "}", localVarApiClient.escapeString(provider.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call inboundProviderPostValidateBeforeCall(@javax.annotation.Nonnull String provider, @javax.annotation.Nonnull Object body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'provider' is set
        if (provider == null) {
            throw new ApiException("Missing the required parameter 'provider' when calling inboundProviderPost(Async)");
        }

        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling inboundProviderPost(Async)");
        }

        return inboundProviderPostCall(provider, body, _callback);

    }

    /**
     * Receive inbound webhook from a provider
     * Accepts webhooks from external providers (Stripe, GitHub, etc.) and routes them to the customer&#39;s endpoints. 
     * @param provider  (required)
     * @param body  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid payload </td><td>  -  </td></tr>
     </table>
     */
    public void inboundProviderPost(@javax.annotation.Nonnull String provider, @javax.annotation.Nonnull Object body) throws ApiException {
        inboundProviderPostWithHttpInfo(provider, body);
    }

    /**
     * Receive inbound webhook from a provider
     * Accepts webhooks from external providers (Stripe, GitHub, etc.) and routes them to the customer&#39;s endpoints. 
     * @param provider  (required)
     * @param body  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid payload </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> inboundProviderPostWithHttpInfo(@javax.annotation.Nonnull String provider, @javax.annotation.Nonnull Object body) throws ApiException {
        okhttp3.Call localVarCall = inboundProviderPostValidateBeforeCall(provider, body, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Receive inbound webhook from a provider (asynchronously)
     * Accepts webhooks from external providers (Stripe, GitHub, etc.) and routes them to the customer&#39;s endpoints. 
     * @param provider  (required)
     * @param body  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid payload </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inboundProviderPostAsync(@javax.annotation.Nonnull String provider, @javax.annotation.Nonnull Object body, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = inboundProviderPostValidateBeforeCall(provider, body, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
