/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EmbedConfigTheme
 */
public class EmbedConfigThemeTest {
    private final EmbedConfigTheme model = new EmbedConfigTheme();

    /**
     * Model tests for EmbedConfigTheme
     */
    @Test
    public void testEmbedConfigTheme() {
        // TODO: test EmbedConfigTheme
    }

    /**
     * Test the property 'primaryColor'
     */
    @Test
    public void primaryColorTest() {
        // TODO: test primaryColor
    }

    /**
     * Test the property 'backgroundColor'
     */
    @Test
    public void backgroundColorTest() {
        // TODO: test backgroundColor
    }

    /**
     * Test the property 'fontFamily'
     */
    @Test
    public void fontFamilyTest() {
        // TODO: test fontFamily
    }

}
