/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InboundWebhookResponse
 */
public class InboundWebhookResponseTest {
    private final InboundWebhookResponse model = new InboundWebhookResponse();

    /**
     * Model tests for InboundWebhookResponse
     */
    @Test
    public void testInboundWebhookResponse() {
        // TODO: test InboundWebhookResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'endpointId'
     */
    @Test
    public void endpointIdTest() {
        // TODO: test endpointId
    }

    /**
     * Test the property 'receivedAt'
     */
    @Test
    public void receivedAtTest() {
        // TODO: test receivedAt
    }

}
