/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LatencyResponse
 */
public class LatencyResponseTest {
    private final LatencyResponse model = new LatencyResponse();

    /**
     * Model tests for LatencyResponse
     */
    @Test
    public void testLatencyResponse() {
        // TODO: test LatencyResponse
    }

    /**
     * Test the property 'p50'
     */
    @Test
    public void p50Test() {
        // TODO: test p50
    }

    /**
     * Test the property 'p90'
     */
    @Test
    public void p90Test() {
        // TODO: test p90
    }

    /**
     * Test the property 'p95'
     */
    @Test
    public void p95Test() {
        // TODO: test p95
    }

    /**
     * Test the property 'p99'
     */
    @Test
    public void p99Test() {
        // TODO: test p99
    }

    /**
     * Test the property 'period'
     */
    @Test
    public void periodTest() {
        // TODO: test period
    }

}
