/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NotificationPreferences
 */
public class NotificationPreferencesTest {
    private final NotificationPreferences model = new NotificationPreferences();

    /**
     * Model tests for NotificationPreferences
     */
    @Test
    public void testNotificationPreferences() {
        // TODO: test NotificationPreferences
    }

    /**
     * Test the property 'emailOnFailure'
     */
    @Test
    public void emailOnFailureTest() {
        // TODO: test emailOnFailure
    }

    /**
     * Test the property 'emailOnDeadLetter'
     */
    @Test
    public void emailOnDeadLetterTest() {
        // TODO: test emailOnDeadLetter
    }

    /**
     * Test the property 'emailOnSuccess'
     */
    @Test
    public void emailOnSuccessTest() {
        // TODO: test emailOnSuccess
    }

    /**
     * Test the property 'slackWebhookUrl'
     */
    @Test
    public void slackWebhookUrlTest() {
        // TODO: test slackWebhookUrl
    }

    /**
     * Test the property 'discordWebhookUrl'
     */
    @Test
    public void discordWebhookUrlTest() {
        // TODO: test discordWebhookUrl
    }

    /**
     * Test the property 'webhookUrl'
     */
    @Test
    public void webhookUrlTest() {
        // TODO: test webhookUrl
    }

}
