/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlatformSettings
 */
public class PlatformSettingsTest {
    private final PlatformSettings model = new PlatformSettings();

    /**
     * Model tests for PlatformSettings
     */
    @Test
    public void testPlatformSettings() {
        // TODO: test PlatformSettings
    }

    /**
     * Test the property 'defaultPlan'
     */
    @Test
    public void defaultPlanTest() {
        // TODO: test defaultPlan
    }

    /**
     * Test the property 'maxEndpointsFree'
     */
    @Test
    public void maxEndpointsFreeTest() {
        // TODO: test maxEndpointsFree
    }

    /**
     * Test the property 'maxEndpointsPro'
     */
    @Test
    public void maxEndpointsProTest() {
        // TODO: test maxEndpointsPro
    }

    /**
     * Test the property 'maxWebhooksFree'
     */
    @Test
    public void maxWebhooksFreeTest() {
        // TODO: test maxWebhooksFree
    }

    /**
     * Test the property 'maxWebhooksPro'
     */
    @Test
    public void maxWebhooksProTest() {
        // TODO: test maxWebhooksPro
    }

    /**
     * Test the property 'rateLimitFree'
     */
    @Test
    public void rateLimitFreeTest() {
        // TODO: test rateLimitFree
    }

    /**
     * Test the property 'rateLimitPro'
     */
    @Test
    public void rateLimitProTest() {
        // TODO: test rateLimitPro
    }

    /**
     * Test the property 'retryMaxAttempts'
     */
    @Test
    public void retryMaxAttemptsTest() {
        // TODO: test retryMaxAttempts
    }

    /**
     * Test the property 'retentionDaysFree'
     */
    @Test
    public void retentionDaysFreeTest() {
        // TODO: test retentionDaysFree
    }

    /**
     * Test the property 'retentionDaysPro'
     */
    @Test
    public void retentionDaysProTest() {
        // TODO: test retentionDaysPro
    }

    /**
     * Test the property 'maintenanceMode'
     */
    @Test
    public void maintenanceModeTest() {
        // TODO: test maintenanceMode
    }

    /**
     * Test the property 'signupEnabled'
     */
    @Test
    public void signupEnabledTest() {
        // TODO: test signupEnabled
    }

    /**
     * Test the property 'planPricePro'
     */
    @Test
    public void planPriceProTest() {
        // TODO: test planPricePro
    }

    /**
     * Test the property 'planPriceBusiness'
     */
    @Test
    public void planPriceBusinessTest() {
        // TODO: test planPriceBusiness
    }

    /**
     * Test the property 'resendApiKey'
     */
    @Test
    public void resendApiKeyTest() {
        // TODO: test resendApiKey
    }

    /**
     * Test the property 'emailSender'
     */
    @Test
    public void emailSenderTest() {
        // TODO: test emailSender
    }

}
