/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.SystemStatsPlanBreakdownInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SystemStats
 */
public class SystemStatsTest {
    private final SystemStats model = new SystemStats();

    /**
     * Model tests for SystemStats
     */
    @Test
    public void testSystemStats() {
        // TODO: test SystemStats
    }

    /**
     * Test the property 'totalUsers'
     */
    @Test
    public void totalUsersTest() {
        // TODO: test totalUsers
    }

    /**
     * Test the property 'activeUsers'
     */
    @Test
    public void activeUsersTest() {
        // TODO: test activeUsers
    }

    /**
     * Test the property 'totalEndpoints'
     */
    @Test
    public void totalEndpointsTest() {
        // TODO: test totalEndpoints
    }

    /**
     * Test the property 'totalDeliveries'
     */
    @Test
    public void totalDeliveriesTest() {
        // TODO: test totalDeliveries
    }

    /**
     * Test the property 'planBreakdown'
     */
    @Test
    public void planBreakdownTest() {
        // TODO: test planBreakdown
    }

}
