/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Monthly revenue data point
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-03T11:26:07.739612497Z[Etc/UTC]", comments = "Generator version: 7.22.0")
public class AdminRevenueEntry {
  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  @javax.annotation.Nonnull
  private LocalDate date;

  public static final String SERIALIZED_NAME_MRR = "mrr";
  @SerializedName(SERIALIZED_NAME_MRR)
  @javax.annotation.Nonnull
  private Double mrr;

  public static final String SERIALIZED_NAME_NEW_SUBSCRIPTIONS = "new_subscriptions";
  @SerializedName(SERIALIZED_NAME_NEW_SUBSCRIPTIONS)
  @javax.annotation.Nonnull
  private Integer newSubscriptions;

  public static final String SERIALIZED_NAME_CHURNS = "churns";
  @SerializedName(SERIALIZED_NAME_CHURNS)
  @javax.annotation.Nonnull
  private Integer churns;

  public AdminRevenueEntry() {
  }

  public AdminRevenueEntry date(@javax.annotation.Nonnull LocalDate date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   */
  @javax.annotation.Nonnull
  public LocalDate getDate() {
    return date;
  }

  public void setDate(@javax.annotation.Nonnull LocalDate date) {
    this.date = date;
  }


  public AdminRevenueEntry mrr(@javax.annotation.Nonnull Double mrr) {
    this.mrr = mrr;
    return this;
  }

  /**
   * Monthly recurring revenue in dollars
   * @return mrr
   */
  @javax.annotation.Nonnull
  public Double getMrr() {
    return mrr;
  }

  public void setMrr(@javax.annotation.Nonnull Double mrr) {
    this.mrr = mrr;
  }


  public AdminRevenueEntry newSubscriptions(@javax.annotation.Nonnull Integer newSubscriptions) {
    this.newSubscriptions = newSubscriptions;
    return this;
  }

  /**
   * Get newSubscriptions
   * @return newSubscriptions
   */
  @javax.annotation.Nonnull
  public Integer getNewSubscriptions() {
    return newSubscriptions;
  }

  public void setNewSubscriptions(@javax.annotation.Nonnull Integer newSubscriptions) {
    this.newSubscriptions = newSubscriptions;
  }


  public AdminRevenueEntry churns(@javax.annotation.Nonnull Integer churns) {
    this.churns = churns;
    return this;
  }

  /**
   * Get churns
   * @return churns
   */
  @javax.annotation.Nonnull
  public Integer getChurns() {
    return churns;
  }

  public void setChurns(@javax.annotation.Nonnull Integer churns) {
    this.churns = churns;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminRevenueEntry adminRevenueEntry = (AdminRevenueEntry) o;
    return Objects.equals(this.date, adminRevenueEntry.date) &&
        Objects.equals(this.mrr, adminRevenueEntry.mrr) &&
        Objects.equals(this.newSubscriptions, adminRevenueEntry.newSubscriptions) &&
        Objects.equals(this.churns, adminRevenueEntry.churns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, mrr, newSubscriptions, churns);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminRevenueEntry {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    mrr: ").append(toIndentedString(mrr)).append("\n");
    sb.append("    newSubscriptions: ").append(toIndentedString(newSubscriptions)).append("\n");
    sb.append("    churns: ").append(toIndentedString(churns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("date", "mrr", "new_subscriptions", "churns"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("date", "mrr", "new_subscriptions", "churns"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AdminRevenueEntry
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AdminRevenueEntry.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AdminRevenueEntry is not found in the empty JSON string", AdminRevenueEntry.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AdminRevenueEntry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AdminRevenueEntry` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AdminRevenueEntry.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AdminRevenueEntry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AdminRevenueEntry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AdminRevenueEntry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AdminRevenueEntry.class));

       return (TypeAdapter<T>) new TypeAdapter<AdminRevenueEntry>() {
           @Override
           public void write(JsonWriter out, AdminRevenueEntry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AdminRevenueEntry read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AdminRevenueEntry given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AdminRevenueEntry
   * @throws IOException if the JSON string is invalid with respect to AdminRevenueEntry
   */
  public static AdminRevenueEntry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AdminRevenueEntry.class);
  }

  /**
   * Convert an instance of AdminRevenueEntry to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

