/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AdminUsersIdGet200ResponseEndpointsInner;
import org.openapitools.client.model.AdminUsersIdGet200ResponseRecentDeliveriesInner;
import org.openapitools.client.model.AdminUsersIdGet200ResponseUsageStats;
import org.openapitools.client.model.UserSummary;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * AdminUsersIdGet200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-03T11:26:07.739612497Z[Etc/UTC]", comments = "Generator version: 7.22.0")
public class AdminUsersIdGet200Response {
  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  @javax.annotation.Nullable
  private UserSummary user;

  public static final String SERIALIZED_NAME_ENDPOINTS = "endpoints";
  @SerializedName(SERIALIZED_NAME_ENDPOINTS)
  @javax.annotation.Nullable
  private List<AdminUsersIdGet200ResponseEndpointsInner> endpoints = new ArrayList<>();

  public static final String SERIALIZED_NAME_RECENT_DELIVERIES = "recent_deliveries";
  @SerializedName(SERIALIZED_NAME_RECENT_DELIVERIES)
  @javax.annotation.Nullable
  private List<AdminUsersIdGet200ResponseRecentDeliveriesInner> recentDeliveries = new ArrayList<>();

  public static final String SERIALIZED_NAME_USAGE_STATS = "usage_stats";
  @SerializedName(SERIALIZED_NAME_USAGE_STATS)
  @javax.annotation.Nullable
  private AdminUsersIdGet200ResponseUsageStats usageStats;

  public AdminUsersIdGet200Response() {
  }

  public AdminUsersIdGet200Response user(@javax.annotation.Nullable UserSummary user) {
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @javax.annotation.Nullable
  public UserSummary getUser() {
    return user;
  }

  public void setUser(@javax.annotation.Nullable UserSummary user) {
    this.user = user;
  }


  public AdminUsersIdGet200Response endpoints(@javax.annotation.Nullable List<AdminUsersIdGet200ResponseEndpointsInner> endpoints) {
    this.endpoints = endpoints;
    return this;
  }

  public AdminUsersIdGet200Response addEndpointsItem(AdminUsersIdGet200ResponseEndpointsInner endpointsItem) {
    if (this.endpoints == null) {
      this.endpoints = new ArrayList<>();
    }
    this.endpoints.add(endpointsItem);
    return this;
  }

  /**
   * Get endpoints
   * @return endpoints
   */
  @javax.annotation.Nullable
  public List<AdminUsersIdGet200ResponseEndpointsInner> getEndpoints() {
    return endpoints;
  }

  public void setEndpoints(@javax.annotation.Nullable List<AdminUsersIdGet200ResponseEndpointsInner> endpoints) {
    this.endpoints = endpoints;
  }


  public AdminUsersIdGet200Response recentDeliveries(@javax.annotation.Nullable List<AdminUsersIdGet200ResponseRecentDeliveriesInner> recentDeliveries) {
    this.recentDeliveries = recentDeliveries;
    return this;
  }

  public AdminUsersIdGet200Response addRecentDeliveriesItem(AdminUsersIdGet200ResponseRecentDeliveriesInner recentDeliveriesItem) {
    if (this.recentDeliveries == null) {
      this.recentDeliveries = new ArrayList<>();
    }
    this.recentDeliveries.add(recentDeliveriesItem);
    return this;
  }

  /**
   * Get recentDeliveries
   * @return recentDeliveries
   */
  @javax.annotation.Nullable
  public List<AdminUsersIdGet200ResponseRecentDeliveriesInner> getRecentDeliveries() {
    return recentDeliveries;
  }

  public void setRecentDeliveries(@javax.annotation.Nullable List<AdminUsersIdGet200ResponseRecentDeliveriesInner> recentDeliveries) {
    this.recentDeliveries = recentDeliveries;
  }


  public AdminUsersIdGet200Response usageStats(@javax.annotation.Nullable AdminUsersIdGet200ResponseUsageStats usageStats) {
    this.usageStats = usageStats;
    return this;
  }

  /**
   * Get usageStats
   * @return usageStats
   */
  @javax.annotation.Nullable
  public AdminUsersIdGet200ResponseUsageStats getUsageStats() {
    return usageStats;
  }

  public void setUsageStats(@javax.annotation.Nullable AdminUsersIdGet200ResponseUsageStats usageStats) {
    this.usageStats = usageStats;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminUsersIdGet200Response adminUsersIdGet200Response = (AdminUsersIdGet200Response) o;
    return Objects.equals(this.user, adminUsersIdGet200Response.user) &&
        Objects.equals(this.endpoints, adminUsersIdGet200Response.endpoints) &&
        Objects.equals(this.recentDeliveries, adminUsersIdGet200Response.recentDeliveries) &&
        Objects.equals(this.usageStats, adminUsersIdGet200Response.usageStats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, endpoints, recentDeliveries, usageStats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminUsersIdGet200Response {\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    endpoints: ").append(toIndentedString(endpoints)).append("\n");
    sb.append("    recentDeliveries: ").append(toIndentedString(recentDeliveries)).append("\n");
    sb.append("    usageStats: ").append(toIndentedString(usageStats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("user", "endpoints", "recent_deliveries", "usage_stats"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AdminUsersIdGet200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AdminUsersIdGet200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AdminUsersIdGet200Response is not found in the empty JSON string", AdminUsersIdGet200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AdminUsersIdGet200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AdminUsersIdGet200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `user`
      if (jsonObj.get("user") != null && !jsonObj.get("user").isJsonNull()) {
        UserSummary.validateJsonElement(jsonObj.get("user"));
      }
      if (jsonObj.get("endpoints") != null && !jsonObj.get("endpoints").isJsonNull()) {
        JsonArray jsonArrayendpoints = jsonObj.getAsJsonArray("endpoints");
        if (jsonArrayendpoints != null) {
          // ensure the json data is an array
          if (!jsonObj.get("endpoints").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `endpoints` to be an array in the JSON string but got `%s`", jsonObj.get("endpoints").toString()));
          }

          // validate the optional field `endpoints` (array)
          for (int i = 0; i < jsonArrayendpoints.size(); i++) {
            AdminUsersIdGet200ResponseEndpointsInner.validateJsonElement(jsonArrayendpoints.get(i));
          };
        }
      }
      if (jsonObj.get("recent_deliveries") != null && !jsonObj.get("recent_deliveries").isJsonNull()) {
        JsonArray jsonArrayrecentDeliveries = jsonObj.getAsJsonArray("recent_deliveries");
        if (jsonArrayrecentDeliveries != null) {
          // ensure the json data is an array
          if (!jsonObj.get("recent_deliveries").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `recent_deliveries` to be an array in the JSON string but got `%s`", jsonObj.get("recent_deliveries").toString()));
          }

          // validate the optional field `recent_deliveries` (array)
          for (int i = 0; i < jsonArrayrecentDeliveries.size(); i++) {
            AdminUsersIdGet200ResponseRecentDeliveriesInner.validateJsonElement(jsonArrayrecentDeliveries.get(i));
          };
        }
      }
      // validate the optional field `usage_stats`
      if (jsonObj.get("usage_stats") != null && !jsonObj.get("usage_stats").isJsonNull()) {
        AdminUsersIdGet200ResponseUsageStats.validateJsonElement(jsonObj.get("usage_stats"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AdminUsersIdGet200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AdminUsersIdGet200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AdminUsersIdGet200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AdminUsersIdGet200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<AdminUsersIdGet200Response>() {
           @Override
           public void write(JsonWriter out, AdminUsersIdGet200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AdminUsersIdGet200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AdminUsersIdGet200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AdminUsersIdGet200Response
   * @throws IOException if the JSON string is invalid with respect to AdminUsersIdGet200Response
   */
  public static AdminUsersIdGet200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AdminUsersIdGet200Response.class);
  }

  /**
   * Convert an instance of AdminUsersIdGet200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

