/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * System-level status for admin dashboard
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-03T11:26:07.739612497Z[Etc/UTC]", comments = "Generator version: 7.22.0")
public class AdminSystemStatus {
  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nonnull
  private String version;

  public static final String SERIALIZED_NAME_UPTIME_SECONDS = "uptime_seconds";
  @SerializedName(SERIALIZED_NAME_UPTIME_SECONDS)
  @javax.annotation.Nonnull
  private Integer uptimeSeconds;

  /**
   * Gets or Sets dbStatus
   */
  @JsonAdapter(DbStatusEnum.Adapter.class)
  public enum DbStatusEnum {
    HEALTHY("healthy"),
    
    DEGRADED("degraded"),
    
    DOWN("down");

    private String value;

    DbStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DbStatusEnum fromValue(String value) {
      for (DbStatusEnum b : DbStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DbStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DbStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DbStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DbStatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DbStatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DB_STATUS = "db_status";
  @SerializedName(SERIALIZED_NAME_DB_STATUS)
  @javax.annotation.Nonnull
  private DbStatusEnum dbStatus;

  /**
   * Gets or Sets redisStatus
   */
  @JsonAdapter(RedisStatusEnum.Adapter.class)
  public enum RedisStatusEnum {
    HEALTHY("healthy"),
    
    DEGRADED("degraded"),
    
    DOWN("down");

    private String value;

    RedisStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RedisStatusEnum fromValue(String value) {
      for (RedisStatusEnum b : RedisStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RedisStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RedisStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RedisStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RedisStatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      RedisStatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_REDIS_STATUS = "redis_status";
  @SerializedName(SERIALIZED_NAME_REDIS_STATUS)
  @javax.annotation.Nonnull
  private RedisStatusEnum redisStatus;

  public static final String SERIALIZED_NAME_QUEUE_DEPTH = "queue_depth";
  @SerializedName(SERIALIZED_NAME_QUEUE_DEPTH)
  @javax.annotation.Nonnull
  private Integer queueDepth;

  public AdminSystemStatus() {
  }

  public AdminSystemStatus version(@javax.annotation.Nonnull String version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nonnull
  public String getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nonnull String version) {
    this.version = version;
  }


  public AdminSystemStatus uptimeSeconds(@javax.annotation.Nonnull Integer uptimeSeconds) {
    this.uptimeSeconds = uptimeSeconds;
    return this;
  }

  /**
   * Get uptimeSeconds
   * @return uptimeSeconds
   */
  @javax.annotation.Nonnull
  public Integer getUptimeSeconds() {
    return uptimeSeconds;
  }

  public void setUptimeSeconds(@javax.annotation.Nonnull Integer uptimeSeconds) {
    this.uptimeSeconds = uptimeSeconds;
  }


  public AdminSystemStatus dbStatus(@javax.annotation.Nonnull DbStatusEnum dbStatus) {
    this.dbStatus = dbStatus;
    return this;
  }

  /**
   * Get dbStatus
   * @return dbStatus
   */
  @javax.annotation.Nonnull
  public DbStatusEnum getDbStatus() {
    return dbStatus;
  }

  public void setDbStatus(@javax.annotation.Nonnull DbStatusEnum dbStatus) {
    this.dbStatus = dbStatus;
  }


  public AdminSystemStatus redisStatus(@javax.annotation.Nonnull RedisStatusEnum redisStatus) {
    this.redisStatus = redisStatus;
    return this;
  }

  /**
   * Get redisStatus
   * @return redisStatus
   */
  @javax.annotation.Nonnull
  public RedisStatusEnum getRedisStatus() {
    return redisStatus;
  }

  public void setRedisStatus(@javax.annotation.Nonnull RedisStatusEnum redisStatus) {
    this.redisStatus = redisStatus;
  }


  public AdminSystemStatus queueDepth(@javax.annotation.Nonnull Integer queueDepth) {
    this.queueDepth = queueDepth;
    return this;
  }

  /**
   * Number of pending jobs in the delivery queue
   * @return queueDepth
   */
  @javax.annotation.Nonnull
  public Integer getQueueDepth() {
    return queueDepth;
  }

  public void setQueueDepth(@javax.annotation.Nonnull Integer queueDepth) {
    this.queueDepth = queueDepth;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminSystemStatus adminSystemStatus = (AdminSystemStatus) o;
    return Objects.equals(this.version, adminSystemStatus.version) &&
        Objects.equals(this.uptimeSeconds, adminSystemStatus.uptimeSeconds) &&
        Objects.equals(this.dbStatus, adminSystemStatus.dbStatus) &&
        Objects.equals(this.redisStatus, adminSystemStatus.redisStatus) &&
        Objects.equals(this.queueDepth, adminSystemStatus.queueDepth);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, uptimeSeconds, dbStatus, redisStatus, queueDepth);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminSystemStatus {\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    uptimeSeconds: ").append(toIndentedString(uptimeSeconds)).append("\n");
    sb.append("    dbStatus: ").append(toIndentedString(dbStatus)).append("\n");
    sb.append("    redisStatus: ").append(toIndentedString(redisStatus)).append("\n");
    sb.append("    queueDepth: ").append(toIndentedString(queueDepth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("version", "uptime_seconds", "db_status", "redis_status", "queue_depth"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("version", "uptime_seconds", "db_status", "redis_status", "queue_depth"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AdminSystemStatus
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AdminSystemStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AdminSystemStatus is not found in the empty JSON string", AdminSystemStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AdminSystemStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AdminSystemStatus` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AdminSystemStatus.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("version").toString()));
      }
      if (!jsonObj.get("db_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `db_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("db_status").toString()));
      }
      // validate the required field `db_status`
      DbStatusEnum.validateJsonElement(jsonObj.get("db_status"));
      if (!jsonObj.get("redis_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `redis_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("redis_status").toString()));
      }
      // validate the required field `redis_status`
      RedisStatusEnum.validateJsonElement(jsonObj.get("redis_status"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AdminSystemStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AdminSystemStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AdminSystemStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AdminSystemStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<AdminSystemStatus>() {
           @Override
           public void write(JsonWriter out, AdminSystemStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AdminSystemStatus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AdminSystemStatus given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AdminSystemStatus
   * @throws IOException if the JSON string is invalid with respect to AdminSystemStatus
   */
  public static AdminSystemStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AdminSystemStatus.class);
  }

  /**
   * Convert an instance of AdminSystemStatus to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

