/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Endpoint health metrics and status
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-03T11:26:07.739612497Z[Etc/UTC]", comments = "Generator version: 7.22.0")
public class EndpointHealth {
  public static final String SERIALIZED_NAME_ENDPOINT_ID = "endpoint_id";
  @SerializedName(SERIALIZED_NAME_ENDPOINT_ID)
  @javax.annotation.Nonnull
  private UUID endpointId;

  public static final String SERIALIZED_NAME_IS_HEALTHY = "is_healthy";
  @SerializedName(SERIALIZED_NAME_IS_HEALTHY)
  @javax.annotation.Nonnull
  private Boolean isHealthy;

  public static final String SERIALIZED_NAME_FAILURE_STREAK = "failure_streak";
  @SerializedName(SERIALIZED_NAME_FAILURE_STREAK)
  @javax.annotation.Nullable
  private Integer failureStreak;

  public static final String SERIALIZED_NAME_AVG_RESPONSE_MS = "avg_response_ms";
  @SerializedName(SERIALIZED_NAME_AVG_RESPONSE_MS)
  @javax.annotation.Nullable
  private Integer avgResponseMs;

  public static final String SERIALIZED_NAME_LAST_FAILURE_AT = "last_failure_at";
  @SerializedName(SERIALIZED_NAME_LAST_FAILURE_AT)
  @javax.annotation.Nullable
  private OffsetDateTime lastFailureAt;

  public static final String SERIALIZED_NAME_SUCCESS_RATE = "success_rate";
  @SerializedName(SERIALIZED_NAME_SUCCESS_RATE)
  @javax.annotation.Nullable
  private Double successRate;

  public static final String SERIALIZED_NAME_AVG_LATENCY_MS = "avg_latency_ms";
  @SerializedName(SERIALIZED_NAME_AVG_LATENCY_MS)
  @javax.annotation.Nullable
  private BigDecimal avgLatencyMs;

  public static final String SERIALIZED_NAME_LAST_DELIVERY_AT = "last_delivery_at";
  @SerializedName(SERIALIZED_NAME_LAST_DELIVERY_AT)
  @javax.annotation.Nullable
  private OffsetDateTime lastDeliveryAt;

  public static final String SERIALIZED_NAME_TOTAL_DELIVERIES = "total_deliveries";
  @SerializedName(SERIALIZED_NAME_TOTAL_DELIVERIES)
  @javax.annotation.Nullable
  private Integer totalDeliveries;

  public static final String SERIALIZED_NAME_FAILED_DELIVERIES = "failed_deliveries";
  @SerializedName(SERIALIZED_NAME_FAILED_DELIVERIES)
  @javax.annotation.Nullable
  private Integer failedDeliveries;

  public EndpointHealth() {
  }

  public EndpointHealth endpointId(@javax.annotation.Nonnull UUID endpointId) {
    this.endpointId = endpointId;
    return this;
  }

  /**
   * Get endpointId
   * @return endpointId
   */
  @javax.annotation.Nonnull
  public UUID getEndpointId() {
    return endpointId;
  }

  public void setEndpointId(@javax.annotation.Nonnull UUID endpointId) {
    this.endpointId = endpointId;
  }


  public EndpointHealth isHealthy(@javax.annotation.Nonnull Boolean isHealthy) {
    this.isHealthy = isHealthy;
    return this;
  }

  /**
   * Get isHealthy
   * @return isHealthy
   */
  @javax.annotation.Nonnull
  public Boolean getIsHealthy() {
    return isHealthy;
  }

  public void setIsHealthy(@javax.annotation.Nonnull Boolean isHealthy) {
    this.isHealthy = isHealthy;
  }


  public EndpointHealth failureStreak(@javax.annotation.Nullable Integer failureStreak) {
    this.failureStreak = failureStreak;
    return this;
  }

  /**
   * Get failureStreak
   * @return failureStreak
   */
  @javax.annotation.Nullable
  public Integer getFailureStreak() {
    return failureStreak;
  }

  public void setFailureStreak(@javax.annotation.Nullable Integer failureStreak) {
    this.failureStreak = failureStreak;
  }


  public EndpointHealth avgResponseMs(@javax.annotation.Nullable Integer avgResponseMs) {
    this.avgResponseMs = avgResponseMs;
    return this;
  }

  /**
   * Get avgResponseMs
   * @return avgResponseMs
   */
  @javax.annotation.Nullable
  public Integer getAvgResponseMs() {
    return avgResponseMs;
  }

  public void setAvgResponseMs(@javax.annotation.Nullable Integer avgResponseMs) {
    this.avgResponseMs = avgResponseMs;
  }


  public EndpointHealth lastFailureAt(@javax.annotation.Nullable OffsetDateTime lastFailureAt) {
    this.lastFailureAt = lastFailureAt;
    return this;
  }

  /**
   * Get lastFailureAt
   * @return lastFailureAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastFailureAt() {
    return lastFailureAt;
  }

  public void setLastFailureAt(@javax.annotation.Nullable OffsetDateTime lastFailureAt) {
    this.lastFailureAt = lastFailureAt;
  }


  public EndpointHealth successRate(@javax.annotation.Nullable Double successRate) {
    this.successRate = successRate;
    return this;
  }

  /**
   * Success rate as a fraction (0.0–1.0)
   * @return successRate
   */
  @javax.annotation.Nullable
  public Double getSuccessRate() {
    return successRate;
  }

  public void setSuccessRate(@javax.annotation.Nullable Double successRate) {
    this.successRate = successRate;
  }


  public EndpointHealth avgLatencyMs(@javax.annotation.Nullable BigDecimal avgLatencyMs) {
    this.avgLatencyMs = avgLatencyMs;
    return this;
  }

  /**
   * Average delivery latency in milliseconds
   * @return avgLatencyMs
   */
  @javax.annotation.Nullable
  public BigDecimal getAvgLatencyMs() {
    return avgLatencyMs;
  }

  public void setAvgLatencyMs(@javax.annotation.Nullable BigDecimal avgLatencyMs) {
    this.avgLatencyMs = avgLatencyMs;
  }


  public EndpointHealth lastDeliveryAt(@javax.annotation.Nullable OffsetDateTime lastDeliveryAt) {
    this.lastDeliveryAt = lastDeliveryAt;
    return this;
  }

  /**
   * Get lastDeliveryAt
   * @return lastDeliveryAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastDeliveryAt() {
    return lastDeliveryAt;
  }

  public void setLastDeliveryAt(@javax.annotation.Nullable OffsetDateTime lastDeliveryAt) {
    this.lastDeliveryAt = lastDeliveryAt;
  }


  public EndpointHealth totalDeliveries(@javax.annotation.Nullable Integer totalDeliveries) {
    this.totalDeliveries = totalDeliveries;
    return this;
  }

  /**
   * Get totalDeliveries
   * @return totalDeliveries
   */
  @javax.annotation.Nullable
  public Integer getTotalDeliveries() {
    return totalDeliveries;
  }

  public void setTotalDeliveries(@javax.annotation.Nullable Integer totalDeliveries) {
    this.totalDeliveries = totalDeliveries;
  }


  public EndpointHealth failedDeliveries(@javax.annotation.Nullable Integer failedDeliveries) {
    this.failedDeliveries = failedDeliveries;
    return this;
  }

  /**
   * Get failedDeliveries
   * @return failedDeliveries
   */
  @javax.annotation.Nullable
  public Integer getFailedDeliveries() {
    return failedDeliveries;
  }

  public void setFailedDeliveries(@javax.annotation.Nullable Integer failedDeliveries) {
    this.failedDeliveries = failedDeliveries;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EndpointHealth endpointHealth = (EndpointHealth) o;
    return Objects.equals(this.endpointId, endpointHealth.endpointId) &&
        Objects.equals(this.isHealthy, endpointHealth.isHealthy) &&
        Objects.equals(this.failureStreak, endpointHealth.failureStreak) &&
        Objects.equals(this.avgResponseMs, endpointHealth.avgResponseMs) &&
        Objects.equals(this.lastFailureAt, endpointHealth.lastFailureAt) &&
        Objects.equals(this.successRate, endpointHealth.successRate) &&
        Objects.equals(this.avgLatencyMs, endpointHealth.avgLatencyMs) &&
        Objects.equals(this.lastDeliveryAt, endpointHealth.lastDeliveryAt) &&
        Objects.equals(this.totalDeliveries, endpointHealth.totalDeliveries) &&
        Objects.equals(this.failedDeliveries, endpointHealth.failedDeliveries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpointId, isHealthy, failureStreak, avgResponseMs, lastFailureAt, successRate, avgLatencyMs, lastDeliveryAt, totalDeliveries, failedDeliveries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EndpointHealth {\n");
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    isHealthy: ").append(toIndentedString(isHealthy)).append("\n");
    sb.append("    failureStreak: ").append(toIndentedString(failureStreak)).append("\n");
    sb.append("    avgResponseMs: ").append(toIndentedString(avgResponseMs)).append("\n");
    sb.append("    lastFailureAt: ").append(toIndentedString(lastFailureAt)).append("\n");
    sb.append("    successRate: ").append(toIndentedString(successRate)).append("\n");
    sb.append("    avgLatencyMs: ").append(toIndentedString(avgLatencyMs)).append("\n");
    sb.append("    lastDeliveryAt: ").append(toIndentedString(lastDeliveryAt)).append("\n");
    sb.append("    totalDeliveries: ").append(toIndentedString(totalDeliveries)).append("\n");
    sb.append("    failedDeliveries: ").append(toIndentedString(failedDeliveries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("endpoint_id", "is_healthy", "failure_streak", "avg_response_ms", "last_failure_at", "success_rate", "avg_latency_ms", "last_delivery_at", "total_deliveries", "failed_deliveries"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("endpoint_id", "is_healthy"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EndpointHealth
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EndpointHealth.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in EndpointHealth is not found in the empty JSON string", EndpointHealth.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EndpointHealth.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `EndpointHealth` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EndpointHealth.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("endpoint_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `endpoint_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endpoint_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EndpointHealth.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EndpointHealth' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EndpointHealth> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EndpointHealth.class));

       return (TypeAdapter<T>) new TypeAdapter<EndpointHealth>() {
           @Override
           public void write(JsonWriter out, EndpointHealth value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EndpointHealth read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EndpointHealth given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EndpointHealth
   * @throws IOException if the JSON string is invalid with respect to EndpointHealth
   */
  public static EndpointHealth fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EndpointHealth.class);
  }

  /**
   * Convert an instance of EndpointHealth to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

