/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TwoFactorRequiredResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-03T11:26:07.739612497Z[Etc/UTC]", comments = "Generator version: 7.22.0")
public class TwoFactorRequiredResponse {
  public static final String SERIALIZED_NAME_REQUIRES2FA = "requires_2fa";
  @SerializedName(SERIALIZED_NAME_REQUIRES2FA)
  @javax.annotation.Nonnull
  private Boolean requires2fa;

  public static final String SERIALIZED_NAME_TEMP_TOKEN = "temp_token";
  @SerializedName(SERIALIZED_NAME_TEMP_TOKEN)
  @javax.annotation.Nonnull
  private String tempToken;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nonnull
  private String message;

  public TwoFactorRequiredResponse() {
  }

  public TwoFactorRequiredResponse requires2fa(@javax.annotation.Nonnull Boolean requires2fa) {
    this.requires2fa = requires2fa;
    return this;
  }

  /**
   * Get requires2fa
   * @return requires2fa
   */
  @javax.annotation.Nonnull
  public Boolean getRequires2fa() {
    return requires2fa;
  }

  public void setRequires2fa(@javax.annotation.Nonnull Boolean requires2fa) {
    this.requires2fa = requires2fa;
  }


  public TwoFactorRequiredResponse tempToken(@javax.annotation.Nonnull String tempToken) {
    this.tempToken = tempToken;
    return this;
  }

  /**
   * Get tempToken
   * @return tempToken
   */
  @javax.annotation.Nonnull
  public String getTempToken() {
    return tempToken;
  }

  public void setTempToken(@javax.annotation.Nonnull String tempToken) {
    this.tempToken = tempToken;
  }


  public TwoFactorRequiredResponse message(@javax.annotation.Nonnull String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nonnull
  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nonnull String message) {
    this.message = message;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TwoFactorRequiredResponse twoFactorRequiredResponse = (TwoFactorRequiredResponse) o;
    return Objects.equals(this.requires2fa, twoFactorRequiredResponse.requires2fa) &&
        Objects.equals(this.tempToken, twoFactorRequiredResponse.tempToken) &&
        Objects.equals(this.message, twoFactorRequiredResponse.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requires2fa, tempToken, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TwoFactorRequiredResponse {\n");
    sb.append("    requires2fa: ").append(toIndentedString(requires2fa)).append("\n");
    sb.append("    tempToken: ").append(toIndentedString(tempToken)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("requires_2fa", "temp_token", "message"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("requires_2fa", "temp_token", "message"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TwoFactorRequiredResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TwoFactorRequiredResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TwoFactorRequiredResponse is not found in the empty JSON string", TwoFactorRequiredResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TwoFactorRequiredResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TwoFactorRequiredResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TwoFactorRequiredResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("temp_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `temp_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("temp_token").toString()));
      }
      if (!jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TwoFactorRequiredResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TwoFactorRequiredResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TwoFactorRequiredResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TwoFactorRequiredResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<TwoFactorRequiredResponse>() {
           @Override
           public void write(JsonWriter out, TwoFactorRequiredResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TwoFactorRequiredResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TwoFactorRequiredResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TwoFactorRequiredResponse
   * @throws IOException if the JSON string is invalid with respect to TwoFactorRequiredResponse
   */
  public static TwoFactorRequiredResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TwoFactorRequiredResponse.class);
  }

  /**
   * Convert an instance of TwoFactorRequiredResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

