/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Account usage statistics summary
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-03T11:26:07.739612497Z[Etc/UTC]", comments = "Generator version: 7.22.0")
public class UsageStatsResponse {
  public static final String SERIALIZED_NAME_ENDPOINTS_COUNT = "endpoints_count";
  @SerializedName(SERIALIZED_NAME_ENDPOINTS_COUNT)
  @javax.annotation.Nonnull
  private Integer endpointsCount;

  public static final String SERIALIZED_NAME_DELIVERIES_COUNT = "deliveries_count";
  @SerializedName(SERIALIZED_NAME_DELIVERIES_COUNT)
  @javax.annotation.Nonnull
  private Integer deliveriesCount;

  public static final String SERIALIZED_NAME_TEAMS_COUNT = "teams_count";
  @SerializedName(SERIALIZED_NAME_TEAMS_COUNT)
  @javax.annotation.Nonnull
  private Integer teamsCount;

  public static final String SERIALIZED_NAME_STORAGE_USED_BYTES = "storage_used_bytes";
  @SerializedName(SERIALIZED_NAME_STORAGE_USED_BYTES)
  @javax.annotation.Nonnull
  private Integer storageUsedBytes;

  public UsageStatsResponse() {
  }

  public UsageStatsResponse endpointsCount(@javax.annotation.Nonnull Integer endpointsCount) {
    this.endpointsCount = endpointsCount;
    return this;
  }

  /**
   * Number of active endpoints
   * @return endpointsCount
   */
  @javax.annotation.Nonnull
  public Integer getEndpointsCount() {
    return endpointsCount;
  }

  public void setEndpointsCount(@javax.annotation.Nonnull Integer endpointsCount) {
    this.endpointsCount = endpointsCount;
  }


  public UsageStatsResponse deliveriesCount(@javax.annotation.Nonnull Integer deliveriesCount) {
    this.deliveriesCount = deliveriesCount;
    return this;
  }

  /**
   * Total deliveries in current period
   * @return deliveriesCount
   */
  @javax.annotation.Nonnull
  public Integer getDeliveriesCount() {
    return deliveriesCount;
  }

  public void setDeliveriesCount(@javax.annotation.Nonnull Integer deliveriesCount) {
    this.deliveriesCount = deliveriesCount;
  }


  public UsageStatsResponse teamsCount(@javax.annotation.Nonnull Integer teamsCount) {
    this.teamsCount = teamsCount;
    return this;
  }

  /**
   * Number of teams
   * @return teamsCount
   */
  @javax.annotation.Nonnull
  public Integer getTeamsCount() {
    return teamsCount;
  }

  public void setTeamsCount(@javax.annotation.Nonnull Integer teamsCount) {
    this.teamsCount = teamsCount;
  }


  public UsageStatsResponse storageUsedBytes(@javax.annotation.Nonnull Integer storageUsedBytes) {
    this.storageUsedBytes = storageUsedBytes;
    return this;
  }

  /**
   * Storage used in bytes
   * @return storageUsedBytes
   */
  @javax.annotation.Nonnull
  public Integer getStorageUsedBytes() {
    return storageUsedBytes;
  }

  public void setStorageUsedBytes(@javax.annotation.Nonnull Integer storageUsedBytes) {
    this.storageUsedBytes = storageUsedBytes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageStatsResponse usageStatsResponse = (UsageStatsResponse) o;
    return Objects.equals(this.endpointsCount, usageStatsResponse.endpointsCount) &&
        Objects.equals(this.deliveriesCount, usageStatsResponse.deliveriesCount) &&
        Objects.equals(this.teamsCount, usageStatsResponse.teamsCount) &&
        Objects.equals(this.storageUsedBytes, usageStatsResponse.storageUsedBytes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpointsCount, deliveriesCount, teamsCount, storageUsedBytes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageStatsResponse {\n");
    sb.append("    endpointsCount: ").append(toIndentedString(endpointsCount)).append("\n");
    sb.append("    deliveriesCount: ").append(toIndentedString(deliveriesCount)).append("\n");
    sb.append("    teamsCount: ").append(toIndentedString(teamsCount)).append("\n");
    sb.append("    storageUsedBytes: ").append(toIndentedString(storageUsedBytes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("endpoints_count", "deliveries_count", "teams_count", "storage_used_bytes"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("endpoints_count", "deliveries_count", "teams_count", "storage_used_bytes"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UsageStatsResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UsageStatsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in UsageStatsResponse is not found in the empty JSON string", UsageStatsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UsageStatsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UsageStatsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UsageStatsResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UsageStatsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UsageStatsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UsageStatsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UsageStatsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<UsageStatsResponse>() {
           @Override
           public void write(JsonWriter out, UsageStatsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UsageStatsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UsageStatsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UsageStatsResponse
   * @throws IOException if the JSON string is invalid with respect to UsageStatsResponse
   */
  public static UsageStatsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UsageStatsResponse.class);
  }

  /**
   * Convert an instance of UsageStatsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

