/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Application;
import org.openapitools.client.model.ApplicationsIdPutRequest;
import org.openapitools.client.model.ApplicationsPostRequest;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApplicationsApi
 */
@Disabled
public class ApplicationsApiTest {

    private final ApplicationsApi api = new ApplicationsApi();

    /**
     * List applications
     *
     * Returns all applications for the authenticated user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applicationsGetTest() throws ApiException {
        List<Application> response = api.applicationsGet();
        // TODO: test validations
    }

    /**
     * Delete application
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applicationsIdDeleteTest() throws ApiException {
        UUID id = null;
        api.applicationsIdDelete(id);
        // TODO: test validations
    }

    /**
     * Get application
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applicationsIdGetTest() throws ApiException {
        UUID id = null;
        Application response = api.applicationsIdGet(id);
        // TODO: test validations
    }

    /**
     * Update application
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applicationsIdPutTest() throws ApiException {
        UUID id = null;
        ApplicationsIdPutRequest applicationsIdPutRequest = null;
        Application response = api.applicationsIdPut(id, applicationsIdPutRequest);
        // TODO: test validations
    }

    /**
     * Create application
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applicationsPostTest() throws ApiException {
        ApplicationsPostRequest applicationsPostRequest = null;
        Application response = api.applicationsPost(applicationsPostRequest);
        // TODO: test validations
    }

}
