/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ContactRequest;
import org.openapitools.client.model.ContactResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContactApi
 */
@Disabled
public class ContactApiTest {

    private final ContactApi api = new ContactApi();

    /**
     * Send contact form message
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void contactPostTest() throws ApiException {
        ContactRequest contactRequest = null;
        ContactResponse response = api.contactPost(contactRequest);
        // TODO: test validations
    }

}
