/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.RegisterSchemaRequest;
import java.util.UUID;
import org.openapitools.client.model.ValidateEventRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SchemasApi
 */
@Disabled
public class SchemasApiTest {

    private final SchemasApi api = new SchemasApi();

    /**
     * List registered schemas
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void schemasGetTest() throws ApiException {
        api.schemasGet();
        // TODO: test validations
    }

    /**
     * Get schema by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void schemasIdGetTest() throws ApiException {
        UUID id = null;
        api.schemasIdGet(id);
        // TODO: test validations
    }

    /**
     * Validate an event against a schema
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void schemasIdValidatePostTest() throws ApiException {
        UUID id = null;
        ValidateEventRequest validateEventRequest = null;
        api.schemasIdValidatePost(id, validateEventRequest);
        // TODO: test validations
    }

    /**
     * Register a new JSON Schema
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void schemasPostTest() throws ApiException {
        RegisterSchemaRequest registerSchemaRequest = null;
        api.schemasPost(registerSchemaRequest);
        // TODO: test validations
    }

}
