/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ChangeRoleRequest;
import org.openapitools.client.model.CreateTeamRequest;
import org.openapitools.client.model.InviteRequest;
import org.openapitools.client.model.Team;
import org.openapitools.client.model.TeamDetailResponse;
import org.openapitools.client.model.TeamMember;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TeamsApi
 */
@Disabled
public class TeamsApiTest {

    private final TeamsApi api = new TeamsApi();

    /**
     * List teams
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void teamsGetTest() throws ApiException {
        List<Team> response = api.teamsGet();
        // TODO: test validations
    }

    /**
     * Get team details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void teamsIdGetTest() throws ApiException {
        UUID id = null;
        TeamDetailResponse response = api.teamsIdGet(id);
        // TODO: test validations
    }

    /**
     * Invite a member to the team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void teamsIdInvitePostTest() throws ApiException {
        UUID id = null;
        InviteRequest inviteRequest = null;
        api.teamsIdInvitePost(id, inviteRequest);
        // TODO: test validations
    }

    /**
     * List team members
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void teamsIdMembersGetTest() throws ApiException {
        UUID id = null;
        List<TeamMember> response = api.teamsIdMembersGet(id);
        // TODO: test validations
    }

    /**
     * Remove member from team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void teamsIdMembersUidDeleteTest() throws ApiException {
        UUID id = null;
        UUID uid = null;
        api.teamsIdMembersUidDelete(id, uid);
        // TODO: test validations
    }

    /**
     * Change member role
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void teamsIdMembersUidRolePutTest() throws ApiException {
        UUID id = null;
        UUID uid = null;
        ChangeRoleRequest changeRoleRequest = null;
        api.teamsIdMembersUidRolePut(id, uid, changeRoleRequest);
        // TODO: test validations
    }

    /**
     * Create a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void teamsPostTest() throws ApiException {
        CreateTeamRequest createTeamRequest = null;
        Team response = api.teamsPost(createTeamRequest);
        // TODO: test validations
    }

}
