/*
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ApplyTemplateRequest;
import org.openapitools.client.model.ApplyTemplateResponse;
import org.openapitools.client.model.WebhookTemplate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TemplatesApi
 */
@Disabled
public class TemplatesApiTest {

    private final TemplatesApi api = new TemplatesApi();

    /**
     * List available templates
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void templatesGetTest() throws ApiException {
        String category = null;
        List<WebhookTemplate> response = api.templatesGet(category);
        // TODO: test validations
    }

    /**
     * Apply template to an endpoint
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void templatesIdApplyPostTest() throws ApiException {
        String id = null;
        ApplyTemplateRequest applyTemplateRequest = null;
        ApplyTemplateResponse response = api.templatesIdApplyPost(id, applyTemplateRequest);
        // TODO: test validations
    }

    /**
     * Get template by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void templatesIdGetTest() throws ApiException {
        String id = null;
        WebhookTemplate response = api.templatesIdGet(id);
        // TODO: test validations
    }

}
